config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "posts#index"
  resources :posts
  resources :users, only: [:edit, :update, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  validates :address, presence: true
  validates :text, presence: true, unless: :was_attached?

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  def full_address
    [prefecture, address].compact.join('')
  end

  def was_attached?
    self.image.attached?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :posts
  validates :nickname, presence: true
  validates :email,    presence: true
  validates :profile,  presence: true
  validates :hobby,    presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
  
  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post, only: [:edit, :show, :destroy]
  before_action :move_to_index, only: [:edit, :destroy]

  def index
    @posts = Post.all
  end
  
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    post = Post.find(params[:id])
    if post.update(post_params)
      redirect_to post_path(post.id)
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  def show
    @user = @post.user
  end

  private
  def post_params
    params.require(:post).permit(:address, :latitude, :longitude, :text, :image).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def move_to_index
    return if current_user.id == @post.user_id

    redirect_to :index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :show]
  before_action :move_to_show, only: :edit

  def edit
  end

  def update
    user = User.find(params[:id])
    if user.update(user_params)
      redirect_to user_path(user.id)
    else
      render :edit
    end
  end

  def show
    @posts = @user.posts
  end

  private 
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:nickname, :email, :profile, :hobby)
  end

  def move_to_show
    return if current_user.id == @user.id

    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MapMemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <div class="header">
        <div class="">
          <h1><%= link_to "マップメモアプリ(仮)",root_path %></h1>
        </div>
        <% if user_signed_in? %>
          <div class="">
            <%= link_to current_user.nickname, user_path(current_user.id) %>/
            <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete } %>
          </div>
        <% else %>
          <div class="">
            <%= link_to "ログイン", new_user_session_path %>/
            <%= link_to "新規登録", new_user_registration_path %>
          </div>
        <% end %>
      </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: @post, id:'new_post', local: true do |f| %>
  <div class="form-group">
    <%= f.label :address, 'スポット名' %><br>
    <%= f.text_field :address, placeholder: "(例)東京スカイツリー", autofocus: true, class: "form-control", autocomplete: "off" %><br>
    <%= f.label :text, "コメント" %><br>
    <%= f.text_area :text, placeholder: "(例)卒業旅行のとき" %><br>
    <%= f.label :image, '思い出の画像' %><br>
    <div id="previews"></div>
    <%= f.file_field :image %><br><br>
  </div>
    <%= f.submit '投稿する' %> 
<% end %>

app/views/posts/_map.html.erb
<div class="map" id="map"></div>

<script type="text/javascript">
  function initMap() {
    var test ={lat: <%= @post.latitude %>, lng: <%= @post.longitude %>};
    var map = new google.maps.Map(document.getElementById('map'), {
        center: test,
        zoom: 15
    });
    var transitLayer = new google.maps.TransitLayer();
    transitLayer.setMap(map);

    var contentString = '住所: <%= @post.address %>'
    var infowindow = new google.maps.InfoWindow({
        content: contentString
    });

    var marker = new google.maps.Marker({
        position: test,
        map: map,
        title: contentString
    });

    marker.addListener('click', function() {
        infowindow.open(map, marker);
    });
  };
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['API_KEY'] %>&callback=initMap" async defer></script>

app/views/posts/_post.html.erb
<div>
  <div>
    作成者：<%= post.user.nickname %>
  </div>
  <div>
    <%= link_to post.address, post_path(post.id) %>:
  </div>
  <div>
    コメント：<%= post.text %>
  </div><br />
</div>

app/views/posts/edit.html.erb
<div class="main">
<h1>新規お気に入りスポット編集</h1>

<div>
  <%= render partial: "form", locals: { post: @post } %>
</div>
</div>

app/views/posts/index.html.erb
<div class="main">
  <p>お気に入りスポットを記録しよう！</p>

  <% if user_signed_in? %>
    <div>
      <%= link_to "新規投稿", new_post_path %>
    </div>
  <% end %>
  <h2>みんなのお気に入りスポット一覧</h2>
  <div>
    <% @posts.each do |post| %>
      <%= render partial: "posts/post", locals: { post: post } %>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="main">
  <h1>新規お気に入りスポット投稿</h1>

  <div>
    <%= render partial: "form", locals: { post: @post } %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="main">

  <div>
    <div>作成したユーザー：<%= link_to @post.user.nickname, user_path(@user.id) %></div><br>
    <div>お気に入りスポット：<%= @post.address %></div><br>
    <div>コメント：<%= @post.text %></div><br>
    <% if @post.image.present? %>
      <div>思い出写真：</div>
      <div class="item-box-img">
        <%= image_tag @post.image, class: "item-img" %>
      </div>
    <% end %>
  </div>

    <div>思い出の場所：</div>
    <%= render partial: "map", locals: { post: @post }  %>
  
  <div>
    <% if user_signed_in? && current_user.id == @post.user_id %>
      <%= link_to "編集", edit_post_path(@post.id) %>/
      <%= link_to "削除", post_path(@post.id), data:{ turbo_method: :delete } %>
    <% end %>
  </div>
  
</div>

app/views/users/edit.html.erb
<div>
  <h2>アカウント編集画面</h2>

  <%= form_with model:@user, local: true do |f| %>
    <div class="field">
      <%= f.label :nickname, "ニックネーム" %><br />
      <%= f.text_area :nickname, autofocus: true, placeholder: "(例)たなか" %>
    </div>

    <div class="field">
      <%= f.label :email, "メールアドレス" %><br />
      <%= f.email_field :email, autocomplete: "email" %>
    </div>

    <div class="field">
      <%= f.label :profile, "プロフィール" %><br />
      <%= f.text_area :profile, placeholder: "(例)自己紹介文" %>
    </div>

    <div class="field">
      <%= f.label :hobby, "趣味" %><br />
      <%= f.text_area :hobby, placeholder: "(例)テニス、茶道" %>
    </div>

    <div class="actions">
      <%= f.submit "更新する" %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="main">
  <h2><%= @user.nickname %></h2>
  <div>
    <table>
      <tr>
        <th class="">名前：</th>
        <td class=""><%= @user.nickname %></td>
      </tr>
      <tr>
        <th class="">プロフィール：</th>
        <td class=""><%= @user.profile %></td>
      </tr>
      <tr>
        <th class="">趣味：</th>
        <td class=""><%= @user.hobby %></td>
      </tr>
    </table>
    <% if current_user.id == @user.id %>
      <div>
        <%= link_to "アカウント編集", edit_user_path(@user.id) %>
      </div>
    <% end %>
  </div>
  <h2><%= @user.nickname %>さんのお気に入りスポット一覧</h2>
  <div>
    <% @posts.each do |post| %>
      <%= render partial: "posts/post", locals: { post: post } %>
    <% end %>
  </div>
</div>